USE QLNT_TKYC;
GO

-- =========================================================
-- INDEX CHO FOREIGN KEY
-- =========================================================

CREATE INDEX IX_ADDRESS_LANDLORD
ON dbo.ADDRESS(landlord_id);
GO

CREATE INDEX IX_ADDRESS_REGISTRATION
ON dbo.ADDRESS(registration_id);
GO

CREATE INDEX IX_APPROVAL_APPROVER
ON dbo.APPROVAL(approver_id);
GO

CREATE INDEX IX_APPROVAL_REGISTRATION
ON dbo.APPROVAL(registration_id);
GO

CREATE INDEX IX_APPROVAL_REQUEST
ON dbo.APPROVAL(request_id);
GO

CREATE INDEX IX_AUDIT_LOG_USER
ON dbo.AUDIT_LOG(user_id);
GO

CREATE INDEX IX_CONFIGURATION_USER
ON dbo.CONFIGURATION(updated_by);
GO

CREATE INDEX IX_DOCUMENT_REGISTRATION
ON dbo.DOCUMENT(registration_id);
GO

CREATE INDEX IX_DOCUMENT_VERSION_DOCUMENT
ON dbo.DOCUMENT_VERSION(document_id);
GO

CREATE INDEX IX_DOCUMENT_VERSION_USER
ON dbo.DOCUMENT_VERSION(uploaded_by);
GO

CREATE INDEX IX_ESCALATION_USER
ON dbo.ESCALATION(assigned_to);
GO

CREATE INDEX IX_ESCALATION_SLA
ON dbo.ESCALATION(sla_tracking_id);
GO

CREATE INDEX IX_NOTIFICATION_REGISTRATION
ON dbo.NOTIFICATION(registration_id);
GO

CREATE INDEX IX_NOTIFICATION_REQUEST
ON dbo.NOTIFICATION(request_id);
GO

CREATE INDEX IX_NOTIFICATION_USER
ON dbo.NOTIFICATION(user_id);
GO

CREATE INDEX IX_REGISTRATION_STUDENT
ON dbo.REGISTRATION(student_id);
GO

CREATE INDEX IX_REQUEST_CREATED_BY
ON dbo.REQUEST(created_by);
GO

CREATE INDEX IX_REQUEST_PROCESSED_BY
ON dbo.REQUEST(processed_by);
GO

CREATE INDEX IX_REQUEST_REGISTRATION
ON dbo.REQUEST(registration_id);
GO

CREATE INDEX IX_REQUEST_HISTORY_USER
ON dbo.REQUEST_HISTORY(changed_by);
GO

CREATE INDEX IX_REQUEST_HISTORY_REQUEST
ON dbo.REQUEST_HISTORY(request_id);
GO

CREATE INDEX IX_ROLE_PERMISSION_GRANTED_BY
ON dbo.ROLE_PERMISSION(granted_by);
GO

CREATE INDEX IX_ROLE_PERMISSION_PERMISSION
ON dbo.ROLE_PERMISSION(permission_id);
GO

CREATE INDEX IX_SLA_TRACKING_REGISTRATION
ON dbo.SLA_TRACKING(registration_id);
GO

CREATE INDEX IX_SLA_TRACKING_REQUEST
ON dbo.SLA_TRACKING(request_id);
GO

CREATE INDEX IX_USER_ROLE_ASSIGNED_BY
ON dbo.USER_ROLE(assigned_by);
GO

CREATE INDEX IX_USER_ROLE_ROLE
ON dbo.USER_ROLE(role_id);
GO

GO